version: '2'
services:
    php:
      build:
        context: ./php-fpm
      volumes:
        - ./application:/var/www/application:cached
        - ./logs/symfony:/var/www/application/var/logs:cached
        - ./php-fpm/symfony.ini:/etc/php7/conf.d/symfony.ini:ro
        - ./php-fpm/symfony.pool.conf:/etc/php7/php-fpm.d/symfony.pool.conf:ro
      environment:
        - PHP_IDE_CONFIG=serverName=_

    nginx:
      image: nginx:1.11
      ports:
        - "8080:80"
      links:
        - php
      volumes_from:
        - php
      volumes:
        - ./logs/nginx/:/var/log/nginx:cached
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro