version: '2'
services:
    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./php-fpm
        ports:
            - "11078:11078"
        volumes:
            - ./application:/var/www/application:cached
            - ./logs/symfony:/var/www/application/var/logs:cached
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes_from:
           - php
        volumes:
          - ./logs/nginx/:/var/log/nginx:cached