version: '2'
services:
    php:
        build:
          context: ./php-fpm
          args:
            - profiling=${FARO_PROFILING}
            - xdebug=${FARO_XDEBUG}

        volumes:
            - ./application:/var/www/application:cached
            - ./logs/symfony:/var/www/application/var/logs:cached
    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes_from:
           - php
        volumes:
          - ./logs/nginx/:/var/log/nginx:cached