version: '3'
services:

  logger:
    image: sendgridlabs/loggly-docker
    environment: 
      - TAG=Docker
      - TOKEN=${LOGGLY_TOKEN}
    ports:
      - 514/udp
    env_file: 
      - .env

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=app
    volumes:
      - ./data/mysql:/var/lib/mysql
    expose: 
      - 3306
    ports:
      - 8083:3306
            
  application:
    build: .
    image: node:8.3
    working_dir: /app
    command: npm start
    volumes:
      - ./src:/app
      - /app/node_modules
      - ./logs/application:/var/log/application
    ports:
      - 8080:3000
      - 5858:5858
    links:
      - mysql
      - logger
    depends_on:
      - mysql
      - logger
    environment:
      - MYSQL_URL=mysql://root:verysecret@mysql/app
